-- =============================================================
-- Dispatch Architecture V2 (DB-first, idempotent, lock-safe)
-- =============================================================
-- Objetivo:
-- - Llevar la cola, locks, retries y timeouts a Postgres/Supabase.
-- - Evitar doble asignacion/race conditions en workers serverless.
-- - Habilitar idempotencia por event_id/source_event_key.
--
-- Este script es incremental (CREATE IF NOT EXISTS / ALTER IF NOT EXISTS).
-- Aplicar manualmente en Supabase SQL Editor.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- -----------------------------------------------------------------
-- 1) Enums de estado
-- -----------------------------------------------------------------
DO $$ BEGIN
  CREATE TYPE public.trip_event_type_enum AS ENUM (
    'trip_created',
    'trip_queued',
    'dispatch_claimed',
    'driver_selected',
    'driver_notified',
    'driver_accepted',
    'driver_rejected',
    'dispatch_timeout',
    'dispatch_requeued',
    'trip_cancelled',
    'trip_completed',
    'system_error'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.dispatch_status_enum AS ENUM (
    'idle',
    'queued',
    'claimed',
    'driver_notified',
    'waiting_acceptance',
    'retry_wait',
    'accepted',
    'cancelled',
    'completed',
    'dead_letter'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.dispatch_attempt_result_enum AS ENUM (
    'assigned_pending',
    'no_driver_available',
    'notify_failed',
    'claim_lost',
    'accept_timeout',
    'driver_rejected',
    'passenger_cancelled',
    'system_error',
    'skipped'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.notification_status_enum AS ENUM (
    'queued',
    'sending',
    'sent',
    'failed',
    'acknowledged',
    'abandoned'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.notification_channel_enum AS ENUM (
    'push',
    'whatsapp',
    'sms',
    'internal'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE public.driver_presence_status_enum AS ENUM (
    'offline',
    'idle',
    'busy',
    'paused'
  );
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- -----------------------------------------------------------------
-- 2) Hardening incremental de trips (estado persistente)
-- -----------------------------------------------------------------
ALTER TABLE public.trips
  ADD COLUMN IF NOT EXISTS dispatch_status public.dispatch_status_enum NOT NULL DEFAULT 'idle',
  ADD COLUMN IF NOT EXISTS dispatch_attempts INTEGER NOT NULL DEFAULT 0 CHECK (dispatch_attempts >= 0),
  ADD COLUMN IF NOT EXISTS dispatch_token UUID,
  ADD COLUMN IF NOT EXISTS next_dispatch_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS status_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS row_version BIGINT NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_trips_status_next_dispatch
  ON public.trips (status, next_dispatch_at);

CREATE INDEX IF NOT EXISTS idx_trips_dispatch_status_next
  ON public.trips (dispatch_status, next_dispatch_at);

CREATE INDEX IF NOT EXISTS idx_trips_open_by_passenger
  ON public.trips (passenger_phone, created_at DESC)
  WHERE status IN ('queued', 'pending', 'accepted', 'going_to_pickup', 'in_progress');

-- Backfill suave de dispatch_status en filas existentes.
UPDATE public.trips
SET dispatch_status = CASE
  WHEN status = 'queued' THEN 'queued'::public.dispatch_status_enum
  WHEN status = 'pending' THEN 'waiting_acceptance'::public.dispatch_status_enum
  WHEN status IN ('accepted', 'going_to_pickup', 'in_progress') THEN 'accepted'::public.dispatch_status_enum
  WHEN status = 'completed' THEN 'completed'::public.dispatch_status_enum
  WHEN status = 'cancelled' THEN 'cancelled'::public.dispatch_status_enum
  ELSE dispatch_status
END
WHERE dispatch_status = 'idle';

CREATE OR REPLACE FUNCTION public.bump_trip_row_version()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.row_version := COALESCE(OLD.row_version, 0) + 1;
  NEW.status_updated_at := NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_bump_trip_row_version ON public.trips;
CREATE TRIGGER trg_bump_trip_row_version
BEFORE UPDATE ON public.trips
FOR EACH ROW
EXECUTE FUNCTION public.bump_trip_row_version();

-- -----------------------------------------------------------------
-- 3) Event store idempotente (trip_events)
-- -----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.trip_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
  source TEXT NOT NULL,
  source_event_key TEXT,
  trip_id UUID REFERENCES public.trips(id) ON DELETE CASCADE,
  event_type public.trip_event_type_enum NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  processed BOOLEAN NOT NULL DEFAULT FALSE,
  processed_at TIMESTAMPTZ,
  duplicate_count INTEGER NOT NULL DEFAULT 0 CHECK (duplicate_count >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_trip_events_source_key UNIQUE (source, source_event_key)
);

CREATE INDEX IF NOT EXISTS idx_trip_events_trip_created
  ON public.trip_events (trip_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_trip_events_unprocessed
  ON public.trip_events (processed, created_at)
  WHERE processed = FALSE;

CREATE OR REPLACE FUNCTION public.set_trip_events_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_trip_events_updated_at ON public.trip_events;
CREATE TRIGGER trg_trip_events_updated_at
BEFORE UPDATE ON public.trip_events
FOR EACH ROW
EXECUTE FUNCTION public.set_trip_events_updated_at();

CREATE OR REPLACE FUNCTION public.append_trip_event_once(
  p_source TEXT,
  p_source_event_key TEXT,
  p_trip_id UUID,
  p_event_type public.trip_event_type_enum,
  p_payload JSONB DEFAULT '{}'::jsonb
)
RETURNS TABLE (
  inserted BOOLEAN,
  event_row_id BIGINT,
  event_uuid UUID
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF p_source IS NULL OR btrim(p_source) = '' THEN
    RAISE EXCEPTION 'source is required';
  END IF;

  RETURN QUERY
  WITH ins AS (
    INSERT INTO public.trip_events (
      source,
      source_event_key,
      trip_id,
      event_type,
      payload
    )
    VALUES (
      p_source,
      NULLIF(p_source_event_key, ''),
      p_trip_id,
      p_event_type,
      COALESCE(p_payload, '{}'::jsonb)
    )
    ON CONFLICT (source, source_event_key) DO NOTHING
    RETURNING id, event_id
  )
  SELECT TRUE, ins.id, ins.event_id
  FROM ins
  UNION ALL
  SELECT FALSE, e.id, e.event_id
  FROM public.trip_events e
  WHERE e.source = p_source
    AND e.source_event_key = NULLIF(p_source_event_key, '')
    AND NOT EXISTS (SELECT 1 FROM ins)
  LIMIT 1;

  IF p_source_event_key IS NOT NULL AND btrim(p_source_event_key) <> '' THEN
    UPDATE public.trip_events
    SET duplicate_count = duplicate_count + 1,
        updated_at = NOW()
    WHERE source = p_source
      AND source_event_key = p_source_event_key
      AND id NOT IN (
        SELECT id
        FROM public.trip_events
        WHERE source = p_source
          AND source_event_key = p_source_event_key
        ORDER BY created_at ASC
        LIMIT 1
      );
  END IF;
END;
$$;

-- -----------------------------------------------------------------
-- 4) Cola de dispatch persistente (dispatch_queue)
-- -----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.dispatch_queue (
  trip_id UUID PRIMARY KEY REFERENCES public.trips(id) ON DELETE CASCADE,
  passenger_phone TEXT NOT NULL,
  queue_status public.dispatch_status_enum NOT NULL DEFAULT 'queued',
  priority SMALLINT NOT NULL DEFAULT 100,
  enqueued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  attempts_count INTEGER NOT NULL DEFAULT 0 CHECK (attempts_count >= 0),
  max_attempts INTEGER NOT NULL DEFAULT 20 CHECK (max_attempts > 0),
  last_attempt_at TIMESTAMPTZ,
  lock_token UUID,
  lock_owner TEXT,
  lock_acquired_at TIMESTAMPTZ,
  lock_expires_at TIMESTAMPTZ,
  selected_driver_id UUID REFERENCES public.drivers(id) ON DELETE SET NULL,
  selected_distance_km NUMERIC(8,3),
  selected_score NUMERIC(10,4),
  last_error_code TEXT,
  last_error TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_dispatch_queue_ready
  ON public.dispatch_queue (queue_status, next_attempt_at, priority, enqueued_at);

CREATE INDEX IF NOT EXISTS idx_dispatch_queue_lock_expiry
  ON public.dispatch_queue (queue_status, lock_expires_at)
  WHERE queue_status = 'claimed';

CREATE INDEX IF NOT EXISTS idx_dispatch_queue_phone
  ON public.dispatch_queue (passenger_phone, enqueued_at);

CREATE OR REPLACE FUNCTION public.set_dispatch_queue_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_dispatch_queue_updated_at ON public.dispatch_queue;
CREATE TRIGGER trg_dispatch_queue_updated_at
BEFORE UPDATE ON public.dispatch_queue
FOR EACH ROW
EXECUTE FUNCTION public.set_dispatch_queue_updated_at();

CREATE OR REPLACE FUNCTION public.sync_dispatch_queue_from_trips()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    DELETE FROM public.dispatch_queue WHERE trip_id = OLD.id;
    RETURN OLD;
  END IF;

  IF NEW.status = 'queued' THEN
    INSERT INTO public.dispatch_queue (
      trip_id,
      passenger_phone,
      queue_status,
      enqueued_at,
      next_attempt_at,
      priority
    ) VALUES (
      NEW.id,
      COALESCE(NEW.passenger_phone, ''),
      'queued',
      COALESCE(NEW.created_at, NOW()),
      NOW(),
      100
    )
    ON CONFLICT (trip_id) DO UPDATE
    SET
      passenger_phone = COALESCE(EXCLUDED.passenger_phone, public.dispatch_queue.passenger_phone),
      queue_status = 'queued',
      next_attempt_at = NOW(),
      lock_token = NULL,
      lock_owner = NULL,
      lock_acquired_at = NULL,
      lock_expires_at = NULL,
      last_error_code = NULL,
      last_error = NULL,
      updated_at = NOW();

    UPDATE public.trips
    SET dispatch_status = 'queued', next_dispatch_at = NOW()
    WHERE id = NEW.id;

    RETURN NEW;
  END IF;

  DELETE FROM public.dispatch_queue WHERE trip_id = NEW.id;

  IF NEW.status = 'pending' THEN
    UPDATE public.trips
    SET dispatch_status = 'waiting_acceptance', next_dispatch_at = NULL
    WHERE id = NEW.id;
  ELSIF NEW.status IN ('accepted', 'going_to_pickup', 'in_progress') THEN
    UPDATE public.trips
    SET dispatch_status = 'accepted', next_dispatch_at = NULL
    WHERE id = NEW.id;
  ELSIF NEW.status = 'cancelled' THEN
    UPDATE public.trips
    SET dispatch_status = 'cancelled', next_dispatch_at = NULL
    WHERE id = NEW.id;
  ELSIF NEW.status = 'completed' THEN
    UPDATE public.trips
    SET dispatch_status = 'completed', next_dispatch_at = NULL
    WHERE id = NEW.id;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_sync_dispatch_queue_iu ON public.trips;
CREATE TRIGGER trg_sync_dispatch_queue_iu
AFTER INSERT OR UPDATE OF status, passenger_phone, created_at
ON public.trips
FOR EACH ROW
EXECUTE FUNCTION public.sync_dispatch_queue_from_trips();

DROP TRIGGER IF EXISTS trg_sync_dispatch_queue_d ON public.trips;
CREATE TRIGGER trg_sync_dispatch_queue_d
AFTER DELETE ON public.trips
FOR EACH ROW
EXECUTE FUNCTION public.sync_dispatch_queue_from_trips();

-- Backfill inicial de cola.
INSERT INTO public.dispatch_queue (
  trip_id,
  passenger_phone,
  queue_status,
  enqueued_at,
  next_attempt_at,
  priority
)
SELECT
  t.id,
  COALESCE(t.passenger_phone, ''),
  'queued',
  COALESCE(t.created_at, NOW()),
  NOW(),
  100
FROM public.trips t
WHERE t.status = 'queued'
ON CONFLICT (trip_id) DO UPDATE
SET
  passenger_phone = EXCLUDED.passenger_phone,
  queue_status = 'queued',
  next_attempt_at = NOW(),
  lock_token = NULL,
  lock_owner = NULL,
  lock_acquired_at = NULL,
  lock_expires_at = NULL,
  updated_at = NOW();

-- -----------------------------------------------------------------
-- 5) Historial de intentos de dispatch
-- -----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.trip_dispatch_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  trip_id UUID NOT NULL REFERENCES public.trips(id) ON DELETE CASCADE,
  attempt_no INTEGER NOT NULL CHECK (attempt_no > 0),
  dispatch_token UUID NOT NULL UNIQUE,
  queue_claimed_at TIMESTAMPTZ,
  driver_selected_at TIMESTAMPTZ,
  notified_at TIMESTAMPTZ,
  finished_at TIMESTAMPTZ,
  selected_driver_id UUID REFERENCES public.drivers(id) ON DELETE SET NULL,
  selected_distance_km NUMERIC(8,3),
  selected_score NUMERIC(10,4),
  search_elapsed_ms INTEGER,
  expansion_step INTEGER,
  search_radii JSONB,
  candidate_count INTEGER,
  result public.dispatch_attempt_result_enum NOT NULL,
  failure_reason TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_trip_attempt UNIQUE (trip_id, attempt_no)
);

CREATE INDEX IF NOT EXISTS idx_dispatch_attempt_trip_created
  ON public.trip_dispatch_attempts (trip_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_dispatch_attempt_driver_created
  ON public.trip_dispatch_attempts (selected_driver_id, created_at DESC)
  WHERE selected_driver_id IS NOT NULL;

CREATE OR REPLACE FUNCTION public.set_trip_dispatch_attempts_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_trip_dispatch_attempts_updated_at ON public.trip_dispatch_attempts;
CREATE TRIGGER trg_trip_dispatch_attempts_updated_at
BEFORE UPDATE ON public.trip_dispatch_attempts
FOR EACH ROW
EXECUTE FUNCTION public.set_trip_dispatch_attempts_updated_at();

-- -----------------------------------------------------------------
-- 6) Estado y ubicacion de conductores
-- -----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.driver_status (
  driver_id UUID PRIMARY KEY REFERENCES public.drivers(id) ON DELETE CASCADE,
  presence_status public.driver_presence_status_enum NOT NULL DEFAULT 'offline',
  is_available BOOLEAN NOT NULL DEFAULT FALSE,
  busy_trip_id UUID REFERENCES public.trips(id) ON DELETE SET NULL,
  active_dispatch_token UUID,
  accept_timeout_at TIMESTAMPTZ,
  reliability_score NUMERIC(5,2) NOT NULL DEFAULT 100.00 CHECK (reliability_score >= 0 AND reliability_score <= 100),
  last_heartbeat_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_driver_status_available
  ON public.driver_status (is_available, presence_status, updated_at DESC);

CREATE TABLE IF NOT EXISTS public.driver_locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  driver_id UUID NOT NULL REFERENCES public.drivers(id) ON DELETE CASCADE,
  lat DOUBLE PRECISION NOT NULL,
  lng DOUBLE PRECISION NOT NULL,
  accuracy_m DOUBLE PRECISION,
  heading DOUBLE PRECISION,
  speed_kmh DOUBLE PRECISION,
  source TEXT NOT NULL DEFAULT 'app',
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT chk_driver_lat CHECK (lat BETWEEN -90 AND 90),
  CONSTRAINT chk_driver_lng CHECK (lng BETWEEN -180 AND 180)
);

-- Hardening incremental para instalaciones que ya tenian driver_locations
-- sin todas las columnas nuevas.
ALTER TABLE IF EXISTS public.driver_locations
  ADD COLUMN IF NOT EXISTS accuracy_m DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS heading DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS speed_kmh DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS source TEXT,
  ADD COLUMN IF NOT EXISTS recorded_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;

UPDATE public.driver_locations
SET source = 'app'
WHERE source IS NULL;

UPDATE public.driver_locations
SET recorded_at = COALESCE(recorded_at, created_at, NOW())
WHERE recorded_at IS NULL;

UPDATE public.driver_locations
SET created_at = COALESCE(created_at, recorded_at, NOW())
WHERE created_at IS NULL;

ALTER TABLE IF EXISTS public.driver_locations
  ALTER COLUMN source SET DEFAULT 'app',
  ALTER COLUMN source SET NOT NULL,
  ALTER COLUMN recorded_at SET DEFAULT NOW(),
  ALTER COLUMN recorded_at SET NOT NULL,
  ALTER COLUMN created_at SET DEFAULT NOW(),
  ALTER COLUMN created_at SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_driver_locations_driver_time
  ON public.driver_locations (driver_id, recorded_at DESC);

CREATE INDEX IF NOT EXISTS idx_driver_locations_recent
  ON public.driver_locations (recorded_at DESC);

CREATE TABLE IF NOT EXISTS public.driver_penalties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  driver_id UUID NOT NULL REFERENCES public.drivers(id) ON DELETE CASCADE,
  trip_id UUID REFERENCES public.trips(id) ON DELETE SET NULL,
  reason TEXT NOT NULL,
  penalty_points NUMERIC(8,3) NOT NULL DEFAULT 0,
  penalty_km NUMERIC(8,3) NOT NULL DEFAULT 0,
  starts_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_driver_penalties_active
  ON public.driver_penalties (driver_id, active, expires_at);

CREATE INDEX IF NOT EXISTS idx_driver_penalties_trip
  ON public.driver_penalties (trip_id)
  WHERE trip_id IS NOT NULL;

CREATE OR REPLACE FUNCTION public.expire_driver_penalties()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_count INTEGER := 0;
BEGIN
  UPDATE public.driver_penalties
  SET active = FALSE,
      updated_at = NOW()
  WHERE active = TRUE
    AND expires_at IS NOT NULL
    AND expires_at <= NOW();

  GET DIAGNOSTICS v_count = ROW_COUNT;
  RETURN v_count;
END;
$$;

-- -----------------------------------------------------------------
-- 7) Cola de notificaciones (outbox)
-- -----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dedupe_key TEXT NOT NULL,
  trip_id UUID REFERENCES public.trips(id) ON DELETE CASCADE,
  driver_id UUID REFERENCES public.drivers(id) ON DELETE SET NULL,
  passenger_phone TEXT,
  channel public.notification_channel_enum NOT NULL,
  status public.notification_status_enum NOT NULL DEFAULT 'queued',
  template_key TEXT NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  provider_message_id TEXT,
  provider_response JSONB,
  attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  max_attempts INTEGER NOT NULL DEFAULT 5 CHECK (max_attempts > 0),
  next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  sent_at TIMESTAMPTZ,
  acknowledged_at TIMESTAMPTZ,
  last_error TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT uq_notifications_dedupe UNIQUE (dedupe_key)
);

CREATE INDEX IF NOT EXISTS idx_notifications_ready
  ON public.notifications (status, next_attempt_at, created_at)
  WHERE status IN ('queued', 'failed');

CREATE INDEX IF NOT EXISTS idx_notifications_trip
  ON public.notifications (trip_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.set_notifications_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_notifications_updated_at ON public.notifications;
CREATE TRIGGER trg_notifications_updated_at
BEFORE UPDATE ON public.notifications
FOR EACH ROW
EXECUTE FUNCTION public.set_notifications_updated_at();

-- -----------------------------------------------------------------
-- 8) Locks e idempotencia global
-- -----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.idempotency_keys (
  key TEXT PRIMARY KEY,
  scope TEXT NOT NULL,
  request_hash TEXT,
  status TEXT NOT NULL DEFAULT 'started',
  response_payload JSONB,
  first_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_idempotency_scope_last_seen
  ON public.idempotency_keys (scope, last_seen_at DESC);

CREATE TABLE IF NOT EXISTS public.worker_locks (
  lock_key TEXT PRIMARY KEY,
  owner TEXT NOT NULL,
  lock_token UUID NOT NULL,
  acquired_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_worker_locks_expires
  ON public.worker_locks (expires_at);

CREATE OR REPLACE FUNCTION public.acquire_worker_lock(
  p_lock_key TEXT,
  p_owner TEXT,
  p_ttl_seconds INTEGER DEFAULT 30
)
RETURNS TABLE (
  acquired BOOLEAN,
  lock_token UUID,
  expires_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_now TIMESTAMPTZ := NOW();
  v_token UUID := gen_random_uuid();
  v_expires TIMESTAMPTZ := v_now + make_interval(secs => GREATEST(5, COALESCE(p_ttl_seconds, 30)));
BEGIN
  IF p_lock_key IS NULL OR btrim(p_lock_key) = '' THEN
    RETURN QUERY SELECT FALSE, NULL::UUID, NULL::TIMESTAMPTZ;
    RETURN;
  END IF;

  DELETE FROM public.worker_locks
  WHERE lock_key = p_lock_key
    AND expires_at <= v_now;

  INSERT INTO public.worker_locks (lock_key, owner, lock_token, acquired_at, expires_at)
  VALUES (p_lock_key, COALESCE(NULLIF(p_owner, ''), 'worker'), v_token, v_now, v_expires)
  ON CONFLICT (lock_key) DO NOTHING;

  IF FOUND THEN
    RETURN QUERY SELECT TRUE, v_token, v_expires;
  ELSE
    RETURN QUERY SELECT FALSE, NULL::UUID, NULL::TIMESTAMPTZ;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.release_worker_lock(
  p_lock_key TEXT,
  p_lock_token UUID
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  DELETE FROM public.worker_locks
  WHERE lock_key = p_lock_key
    AND lock_token = p_lock_token;
  RETURN FOUND;
END;
$$;

-- -----------------------------------------------------------------
-- 9) Locking de dispatch con FOR UPDATE SKIP LOCKED
-- -----------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.claim_dispatch_queue_batch(
  p_worker TEXT,
  p_limit INTEGER DEFAULT 20,
  p_lock_seconds INTEGER DEFAULT 25
)
RETURNS TABLE (
  trip_id UUID,
  lock_token UUID,
  attempt_no INTEGER,
  passenger_phone TEXT,
  destination_lat DOUBLE PRECISION,
  destination_lng DOUBLE PRECISION,
  enqueued_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_now TIMESTAMPTZ := NOW();
  v_limit INTEGER := GREATEST(1, COALESCE(p_limit, 20));
  v_lock_seconds INTEGER := GREATEST(10, COALESCE(p_lock_seconds, 25));
BEGIN
  -- Recupera claims vencidos (worker muerto/redeploy serverless).
  UPDATE public.dispatch_queue
  SET
    queue_status = 'queued',
    lock_token = NULL,
    lock_owner = NULL,
    lock_acquired_at = NULL,
    lock_expires_at = NULL,
    next_attempt_at = LEAST(next_attempt_at, v_now),
    updated_at = v_now
  WHERE queue_status = 'claimed'
    AND lock_expires_at IS NOT NULL
    AND lock_expires_at <= v_now;

  RETURN QUERY
  WITH candidates AS (
    SELECT dq.trip_id
    FROM public.dispatch_queue dq
    JOIN public.trips t ON t.id = dq.trip_id
    WHERE dq.queue_status = 'queued'
      AND dq.next_attempt_at <= v_now
      AND dq.attempts_count < dq.max_attempts
      AND t.status = 'queued'
    ORDER BY dq.priority ASC, dq.enqueued_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT v_limit
  ),
  claimed AS (
    UPDATE public.dispatch_queue dq
    SET
      queue_status = 'claimed',
      lock_token = gen_random_uuid(),
      lock_owner = COALESCE(NULLIF(p_worker, ''), 'worker'),
      lock_acquired_at = v_now,
      lock_expires_at = v_now + make_interval(secs => v_lock_seconds),
      attempts_count = dq.attempts_count + 1,
      last_attempt_at = v_now,
      updated_at = v_now
    FROM candidates c
    WHERE dq.trip_id = c.trip_id
    RETURNING dq.trip_id, dq.lock_token, dq.attempts_count, dq.enqueued_at
  )
  SELECT
    c.trip_id,
    c.lock_token,
    c.attempts_count AS attempt_no,
    t.passenger_phone,
    t.destination_lat::double precision,
    t.destination_lng::double precision,
    c.enqueued_at
  FROM claimed c
  JOIN public.trips t ON t.id = c.trip_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.release_dispatch_claim(
  p_trip_id UUID,
  p_lock_token UUID,
  p_result TEXT DEFAULT 'retry',
  p_retry_seconds INTEGER DEFAULT 12,
  p_error_code TEXT DEFAULT NULL,
  p_error_text TEXT DEFAULT NULL,
  p_selected_driver UUID DEFAULT NULL,
  p_selected_distance_km NUMERIC DEFAULT NULL,
  p_selected_score NUMERIC DEFAULT NULL
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_result TEXT := LOWER(COALESCE(p_result, 'retry'));
  v_retry_seconds INTEGER := GREATEST(1, COALESCE(p_retry_seconds, 12));
BEGIN
  IF p_trip_id IS NULL OR p_lock_token IS NULL THEN
    RETURN FALSE;
  END IF;

  IF v_result = 'retry' THEN
    UPDATE public.dispatch_queue
    SET
      lock_token = NULL,
      lock_owner = NULL,
      lock_acquired_at = NULL,
      lock_expires_at = NULL,
      next_attempt_at = NOW() + make_interval(secs => v_retry_seconds),
      selected_driver_id = COALESCE(p_selected_driver, selected_driver_id),
      selected_distance_km = COALESCE(p_selected_distance_km, selected_distance_km),
      selected_score = COALESCE(p_selected_score, selected_score),
      last_error_code = NULLIF(p_error_code, ''),
      last_error = NULLIF(p_error_text, ''),
      queue_status = CASE
        WHEN attempts_count >= max_attempts THEN 'dead_letter'::public.dispatch_status_enum
        ELSE 'queued'::public.dispatch_status_enum
      END,
      updated_at = NOW()
    WHERE trip_id = p_trip_id
      AND lock_token = p_lock_token
      AND queue_status = 'claimed';

    RETURN FOUND;
  ELSIF v_result IN ('done', 'accepted', 'cancelled', 'drop') THEN
    DELETE FROM public.dispatch_queue
    WHERE trip_id = p_trip_id
      AND lock_token = p_lock_token
      AND queue_status = 'claimed';
    RETURN FOUND;
  ELSIF v_result = 'dead' THEN
    UPDATE public.dispatch_queue
    SET
      queue_status = 'dead_letter',
      lock_token = NULL,
      lock_owner = NULL,
      lock_acquired_at = NULL,
      lock_expires_at = NULL,
      last_error_code = COALESCE(NULLIF(p_error_code, ''), 'dead_letter'),
      last_error = NULLIF(p_error_text, ''),
      updated_at = NOW()
    WHERE trip_id = p_trip_id
      AND lock_token = p_lock_token
      AND queue_status = 'claimed';
    RETURN FOUND;
  END IF;

  RETURN FALSE;
END;
$$;

-- -----------------------------------------------------------------
-- 10) Compatibilidad temporal con funciones actuales del backend
-- -----------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.claim_trip_queue_item(
  p_trip_id UUID,
  p_worker TEXT DEFAULT NULL,
  p_lock_seconds INTEGER DEFAULT 25
)
RETURNS TABLE (
  claimed BOOLEAN,
  lock_token UUID,
  reason TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_now TIMESTAMPTZ := NOW();
  v_lock_token UUID;
BEGIN
  IF p_trip_id IS NULL THEN
    RETURN QUERY SELECT FALSE, NULL::UUID, 'missing_trip_id';
    RETURN;
  END IF;

  UPDATE public.dispatch_queue
  SET
    queue_status = 'queued',
    lock_token = NULL,
    lock_owner = NULL,
    lock_acquired_at = NULL,
    lock_expires_at = NULL,
    updated_at = v_now
  WHERE trip_id = p_trip_id
    AND queue_status = 'claimed'
    AND lock_expires_at IS NOT NULL
    AND lock_expires_at <= v_now;

  UPDATE public.dispatch_queue
  SET
    queue_status = 'claimed',
    lock_token = gen_random_uuid(),
    lock_owner = COALESCE(NULLIF(p_worker, ''), 'worker'),
    lock_acquired_at = v_now,
    lock_expires_at = v_now + make_interval(secs => GREATEST(10, COALESCE(p_lock_seconds, 25))),
    attempts_count = attempts_count + 1,
    last_attempt_at = v_now,
    updated_at = v_now
  WHERE trip_id = p_trip_id
    AND queue_status = 'queued'
    AND next_attempt_at <= v_now
  RETURNING dispatch_queue.lock_token INTO v_lock_token;

  IF v_lock_token IS NULL THEN
    RETURN QUERY SELECT FALSE, NULL::UUID, 'not_available';
    RETURN;
  END IF;

  RETURN QUERY SELECT TRUE, v_lock_token, 'claimed';
END;
$$;

CREATE OR REPLACE FUNCTION public.release_trip_queue_item(
  p_trip_id UUID,
  p_lock_token UUID,
  p_result TEXT DEFAULT 'retry',
  p_retry_seconds INTEGER DEFAULT 12,
  p_error TEXT DEFAULT NULL
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN public.release_dispatch_claim(
    p_trip_id,
    p_lock_token,
    p_result,
    p_retry_seconds,
    NULL,
    p_error,
    NULL,
    NULL,
    NULL
  );
END;
$$;

-- -----------------------------------------------------------------
-- 11) RLS y permisos (solo service_role)
-- -----------------------------------------------------------------
ALTER TABLE public.trip_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.dispatch_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trip_dispatch_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.driver_status ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.driver_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.driver_penalties ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.idempotency_keys ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.worker_locks ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "service_role_trip_events" ON public.trip_events;
CREATE POLICY "service_role_trip_events"
  ON public.trip_events FOR ALL TO service_role
  USING (TRUE) WITH CHECK (TRUE);

DROP POLICY IF EXISTS "service_role_dispatch_queue" ON public.dispatch_queue;
CREATE POLICY "service_role_dispatch_queue"
  ON public.dispatch_queue FOR ALL TO service_role
  USING (TRUE) WITH CHECK (TRUE);

DROP POLICY IF EXISTS "service_role_trip_dispatch_attempts" ON public.trip_dispatch_attempts;
CREATE POLICY "service_role_trip_dispatch_attempts"
  ON public.trip_dispatch_attempts FOR ALL TO service_role
  USING (TRUE) WITH CHECK (TRUE);

DROP POLICY IF EXISTS "service_role_driver_status" ON public.driver_status;
CREATE POLICY "service_role_driver_status"
  ON public.driver_status FOR ALL TO service_role
  USING (TRUE) WITH CHECK (TRUE);

DROP POLICY IF EXISTS "service_role_driver_locations" ON public.driver_locations;
CREATE POLICY "service_role_driver_locations"
  ON public.driver_locations FOR ALL TO service_role
  USING (TRUE) WITH CHECK (TRUE);

DROP POLICY IF EXISTS "service_role_driver_penalties" ON public.driver_penalties;
CREATE POLICY "service_role_driver_penalties"
  ON public.driver_penalties FOR ALL TO service_role
  USING (TRUE) WITH CHECK (TRUE);

DROP POLICY IF EXISTS "service_role_notifications" ON public.notifications;
CREATE POLICY "service_role_notifications"
  ON public.notifications FOR ALL TO service_role
  USING (TRUE) WITH CHECK (TRUE);

DROP POLICY IF EXISTS "service_role_idempotency_keys" ON public.idempotency_keys;
CREATE POLICY "service_role_idempotency_keys"
  ON public.idempotency_keys FOR ALL TO service_role
  USING (TRUE) WITH CHECK (TRUE);

DROP POLICY IF EXISTS "service_role_worker_locks" ON public.worker_locks;
CREATE POLICY "service_role_worker_locks"
  ON public.worker_locks FOR ALL TO service_role
  USING (TRUE) WITH CHECK (TRUE);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.trip_events TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.dispatch_queue TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.trip_dispatch_attempts TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.driver_status TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.driver_locations TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.driver_penalties TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.notifications TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.idempotency_keys TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.worker_locks TO service_role;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO service_role;

REVOKE ALL ON FUNCTION public.append_trip_event_once(TEXT, TEXT, UUID, public.trip_event_type_enum, JSONB) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.append_trip_event_once(TEXT, TEXT, UUID, public.trip_event_type_enum, JSONB) TO service_role;

REVOKE ALL ON FUNCTION public.claim_dispatch_queue_batch(TEXT, INTEGER, INTEGER) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_dispatch_queue_batch(TEXT, INTEGER, INTEGER) TO service_role;

REVOKE ALL ON FUNCTION public.release_dispatch_claim(UUID, UUID, TEXT, INTEGER, TEXT, TEXT, UUID, NUMERIC, NUMERIC) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.release_dispatch_claim(UUID, UUID, TEXT, INTEGER, TEXT, TEXT, UUID, NUMERIC, NUMERIC) TO service_role;

REVOKE ALL ON FUNCTION public.acquire_worker_lock(TEXT, TEXT, INTEGER) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.acquire_worker_lock(TEXT, TEXT, INTEGER) TO service_role;

REVOKE ALL ON FUNCTION public.release_worker_lock(TEXT, UUID) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.release_worker_lock(TEXT, UUID) TO service_role;

REVOKE ALL ON FUNCTION public.claim_trip_queue_item(UUID, TEXT, INTEGER) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_trip_queue_item(UUID, TEXT, INTEGER) TO service_role;

REVOKE ALL ON FUNCTION public.release_trip_queue_item(UUID, UUID, TEXT, INTEGER, TEXT) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.release_trip_queue_item(UUID, UUID, TEXT, INTEGER, TEXT) TO service_role;

COMMENT ON TABLE public.dispatch_queue IS
'Cola transaccional de dispatch. Worker-safe mediante lock_token + SKIP LOCKED.';

COMMENT ON TABLE public.trip_events IS
'Event store idempotente por source_event_key para evitar doble procesamiento.';

COMMENT ON TABLE public.trip_dispatch_attempts IS
'Historial auditable de cada intento de asignacion de chofer.';
