/**
 * @deprecated Usar whatsmeowLines. Se mantiene como re-export para imports existentes.
 */
export {
  listWasenderLines,
  getDefaultWasenderLine,
  resolveWasenderLine,
  getActiveWasenderLine,
  getWasenderApiKey,
  getActiveWasenderLinePhone,
  runWithWasenderLine,
  injectWasenderLineIntoContext,
  extractWasenderLineFromContext,
  hasAnyWasenderApiKey,
  getWasenderLinesHealth,
  listWhatsmeowLines,
  getDefaultWhatsmeowLine,
  resolveWhatsmeowLine,
  resolveWhatsmeowLineByAgentCode,
  getActiveWhatsmeowLine,
  getActiveWhatsmeowAgentCode,
  getActiveWhatsmeowLinePhone,
  getActiveWhatsmeowApiKey,
  runWithWhatsmeowLine,
  injectWhatsmeowLineIntoContext,
  extractWhatsmeowLineFromContext,
  resolveWhatsmeowLineFromContext,
  buildTripWhatsmeowLineContext,
  resolveWhatsmeowLineForPassenger,
  getPassengerWhatsmeowLine,
  listOtpWhatsmeowCandidateLines,
  PASSENGER_OTP_AGENT_CODE,
  PASSENGER_OTP_LINE_PHONE,
  hasAnyWhatsmeowConfig,
  getWhatsmeowLinesHealth,
} from './whatsmeowLines';
